apiVersion: openchoreo.dev/v1alpha1
kind: SecretReference
metadata:
  name: github-token
  namespace: default
spec:
  template:
    type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: secret/git/github-token
        property: username
    - secretKey: password
      remoteRef:
        key: secret/git/github-token
        property: token
  refreshInterval: 1h
