root = "."
tmp_dir = "tmp/air-collab"

[build]
  cmd = "go build -o ./tmp/air-collab/doclet-collab ./cmd"
  bin = "./tmp/air-collab/doclet-collab"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test\\.go$"]

[log]
  time = true
